Add URL validation to CI

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -46,6 +46,14 @@ jobs:
             printf "ERROR: git diff non empty, metadata needs updating, please run the following command:\npython benchmarks/merge_metadata.py"
             exit 1
           fi
+          python tests/validate_urls.py
+          if git diff --quiet; then
+            echo "git diff is empty, benchmark URLs conform to expected format"
+          else
+            git diff
+            printf "ERROR: benchmark URLs do not match expected format, please run the following command:\npython tests/validate_urls.py"
+            exit 1
+          fi
           python tests/validate_results.py
 
       - name: Run Streamlit App Action
