Improve CI checks for 4 cases

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -48,7 +48,15 @@ jobs:
             printf "ERROR: benchmark URLs do not match expected format, please run the following command:\npython tests/validate_urls.py"
             exit 1
           fi
-          python benchmarks/merge_metadata.py
+          python benchmarks/merge_metadata.py 2>&1 | tee merge_metadata.log
+          if grep -i "warning" merge_metadata.log; then
+              echo "ERROR: merge_metadata.py produced warnings"
+              exit 1
+          fi
+          if [ "${PIPESTATUS[0]}" -ne 0 ]; then
+              echo "ERROR: merge_metadata.py failed"
+              exit 1
+          fi
           if git diff --quiet; then
             echo "git diff is empty, metadata must be up to date"
           else
@@ -103,10 +111,11 @@ jobs:
         shell: bash -el {0}
         run: |
           ./runner/benchmark_all.sh -y "tests" tests/sample_benchmarks_metadata.yaml
+          ./runner/benchmark_all.sh -y "tests" results/metadata_subset.yaml
           echo ""
           cat results/benchmark_results.csv
-          if awk -F',' 'NR>1 {if ($6 != "ok") exit 1}' results/benchmark_results.csv; then
-            echo "All benchmarks ran successfully."
+          if awk -F',' 'NR>1 && $3 != "glpk" {if ($6 != "ok") exit 1}' results/benchmark_results.csv; then
+            echo "All non-GLPK benchmarks ran successfully."
           else
             echo "Some benchmarks did not complete successfully."
             exit 1
@@ -114,6 +123,7 @@ jobs:
 
   accessibility-check:
     runs-on: ubuntu-latest
+
     steps:
       - uses: actions/checkout@v4
 
